/* eslint-disable prettier/prettier */
export enum MuscleGroup {
    CHEST = 'CHEST',
    BACK = 'BACK',
    SHOULDERS = 'SHOULDERS',
    QUADRICEPS = 'QUADRICEPS',
    BICEPS_FEMORIS = 'BICEPS_FEMORIS',
    ABDUCTORS = 'ABDUCTORS',
    ADDUCTORS = 'ADDUCTORS',
    CALFS = 'CALFS',
    TRICEPS = 'TRICEPS',
    BICEPS = 'BICEPS',
    ABS = 'ABS',
    UPPER_PART = 'UPPER_PART',
    CORE_STABILITY = 'CORE_STABILITY',
    CORE_STRENGTH = 'CORE_STRENGTH',
    GLUTES = 'GLUTES',
}